Parameters: 
  myKeyPair: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
  NetworkStackNameParameter:
    Type: String
    Default: "jenkins-vpc"

Resources:

  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.small
      ImageId: ami-0c101f26f147fa7fd
      KeyName: !Ref myKeyPair
      AvailabilityZone: "us-east-1a" 
      SecurityGroupIds:
        - Fn::ImportValue: !Sub "${NetworkStackNameParameter}-SecurityGroupID"
      SubnetId: 
        Fn::ImportValue: !Sub "${NetworkStackNameParameter}-SubnetID"
      UserData:
        Fn::Base64:
          !Sub |
             #!/bin/bash
             yum update -y

  ElasticIP:
    Type: 'AWS::EC2::EIP' 
    Properties:
      Domain: VPC
      InstanceId: !Ref Ec2Instance  
      
