Parameters: 
  myKeyPair: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
  NetworkStackNameParameter:
    Type: String
    Default: "wordpress-vpc"
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64'

Resources:

  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.small
      ImageId: !Ref LatestAmiId  
      KeyName: !Ref myKeyPair
      AvailabilityZone: "us-east-1a" 
      SecurityGroupIds:
        - Fn::ImportValue: !Sub "${NetworkStackNameParameter}-SecurityGroupID"
      SubnetId: 
        Fn::ImportValue: !Sub "${NetworkStackNameParameter}-SubnetID"
      Tags:
        - Key: Content Managment System
          Value: WordPress
      UserData:
        Fn::Base64:
          !Sub |
             #!/bin/bash
             cd /home/ec2-user
             sudo dnf upgrade -y
             sudo dnf install -y httpd wget php-fpm php-mysqli php-json php php-devel
             sudo dnf install mariadb105-server 
             sudo systemctl start httpd
             sudo systemctl enable httpd
             wget https://wordpress.org/latest.tar.gz
             tar -xzf latest.tar.gz
             sudo systemctl start mariadb httpd

  ElasticIP:
    Type: 'AWS::EC2::EIP' 
    Properties:
      Domain: VPC
      InstanceId: !Ref Ec2Instance  
      
